### ISSUE TITLE
Question: where can one make contributions to the TennoTools UI?

### ISSUE THREAD

**Issue by EnzoMartin** [makelon/worldstate-server#5]
It's entirely possible I'm blind and missed it but I haven't found the repo that contains the frontend UI for TennoTools. I'd like to contribute adding a few simple filters to the Invasions list for automatically hiding invasions that have items that are not desired by the player.

**Comment by makelon** [comment]
The frontend code isn't publicly available, so it's difficult to contribute at the moment. I'm working on some changes that will let me share it, but it will take some time.

Automatically hiding things that aren't interesting is a nice idea. It'd be great to see that feature added when the repository is public.

**Comment by EnzoMartin** [comment]
If the blocker for sharing it is not related to credentials in the repo, I'm comfortable with whatever state the codebase is in or to be added as a contributor if you want to keep it private for now

**Comment by makelon** [comment]
It's mainly a tooling problem. I didn't expect the project to get as many users as it did, so I just put together something that would work for me. The folder structure and image assets need to be cleaned up a bit to make it easier to build the project.

**Comment by EnzoMartin** [comment]
Gotcha, makes sense, I'm happy to give it a whirl if you're willing. Building the tooling/pipeline tends to be the part I enjoy the most with projects; I especially like the mindset that NextJS employs in regards to bundling and compiling web assets

**Comment by makelon** [comment]
Sorry for the slow responses. I've done some cleanup in the last few weeks.

I sent an invite to the repo if you still want to check it out. I'll make it public once I've had some more time to fix the remaining issues.

**Comment by EnzoMartin** [comment]
No worries, I know how life can be busy 😁

Awesome, thanks, been a while since I've touched angular (it's been React for the past 6 years), will dig into it this week 👍👍
